# Generated by Django 4.2.4 on 2023-09-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_set_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='set',
        ),
    ]
